 # Chapter 2. 파이썬 기본

# 2.1 사칙 연산
## 2.1.1 사칙 연산의 이용
Shift + Enter를 누르면 답이 나온다.

In [1]:
1 + 2

3

In [2]:
(1 + 2 * 3 - 4) / 5

0.6

## 2.1.2 제곱

In [3]:
2 ** 8

256

# 2.2 변수
## 2.2.1 변수를 이용한 계산

In [4]:
x = 1
y = 1/3
x + y

1.3333333333333333

# 2.2.2 변수명의 표기

In [6]:
Data_1 = 1 / 5
Data_2 = 3 / 5
Data_1 + Data_2

0.8

변수명에는 알파벳, 숫자, 밑줄을 사용할 수 있다. 대문자와 소문자를 구별한다. 그러나 변수명의 첫 문자에는 숫자를 사용할 수 없다.

# 2.3 자료형
## 2.3.1 자료형의 종류


자료형 | 사용 예 | 자료형의 의미
-------| --------| -------------| 
int형 | a= 1 | 정수 
float 형 | a = 1.5 | 실수
str 형 | a = "learning" 또는 b = 'abc' | 문자열
bool형 | True 또는 False | 참과 거짓
list 형 | a = [1, 2, 3] | 배열
tuple 형 | a = (1, 2, 3) 또는 b=(2,) | 배열(수정 불가능)
ndarray 형 | a = np.array([1,2,3]) | 행렬

## 2.3.2 type으로 자료형 알아보기

In [7]:
type(100)

int

In [8]:
type(100.1)

float

In [9]:
x = 100
type(x)

int

In [10]:
x = 100.1
type(x)

float

## 2.3.3 문자열

In [12]:
x = 'learning'
type(x)

str

이와 같이 작은따옴표(') 또는 큰따옴표('')로 둘러싸면 문자열로 인식한다.

# 2.4 print 문
## 2.4.1 print 문의 이용
주피터 노트북에서 변수명을 입력해 실행하는 것만으로 그 내용이 표시되지만, 셀의 마지막 행에 적어야만 한다. 

In [13]:
x = 1 / 3
x
y = 2 / 3
y

0.6666666666666666

In [14]:
x = 1 / 3
print(x)
y = 2 / 3
print(y)

0.3333333333333333
0.6666666666666666


## 2.4.2 문자열과 수치를 함께 표시 1

In [15]:
print(' x= ' + str(x))

 x= 0.3333333333333333


str(x)는 float 형의 x를 str 형으로 반환한다. '+'는 int형이나 float형에서는 덧셈이라는 의미가 있지만, str형에서는 두 str 형 값을 연결하는 역할을 한다.

## 2.4.3 문자열과 수치를 함께 표시 2

In [16]:
print('weight = {0} kg'.format(x))

weight = 0.3333333333333333 kg


**'문자열'.format(x)**로 마침표가 있다는 점에 주의한다.

In [18]:
x = 1 / 3
y = 1 / 7
z = 1 / 4
print('weight: {0} kg, {1} kg, {2} kg'.format(x,y,z))

weight: 0.3333333333333333 kg, 0.14285714285714285 kg, 0.25 kg


  **{수치:.nf}**를 입력하면 소수점 이하 n자리까지 표시한다.

In [19]:
print('weight: {0:.2f}kg, y = {1:.2f}kg, z = {2:.2f} kg'.format(x,y,z))

weight: 0.33kg, y = 0.14kg, z = 0.25 kg


# 2.5 list
## 2.5.1 list의 이용
여러 데이터를 하나의 단위로 취급하고 싶은 경우, 즉 배열 변수를 사용하고 싶은 경우에는 list(리스트)형을 사용한다. list는 **리스트명[]**을 사용하여 나타낸다.

In [20]:
x = [1, 1, 2, 3, 5]
print(x)

[1, 1, 2, 3, 5]


각 성분은 **리스트명[요소 번호]**로 참조(확인)할 수 있다. 파이썬에서 배열의 요소 번호(인덱스)는 0부터 시작한다.

In [21]:
x[0]

1

In [23]:
x[3]

3

In [24]:
print(type(x))
print(type(x[0]))

<class 'list'>
<class 'int'>


x는 int형으로 구성된 list형이다. 

In [26]:
s = ['SUN', 1, 'MON', 2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


## 2.5.2 2차원 배열
list형은 2차원 배열 형태로도 만들 수 있다.

In [28]:
a = [[1,2,3], [4,5,6]]
print(a)
print(a[0][1])

[[1, 2, 3], [4, 5, 6]]
2


list요소를 수정하려면 **리스트명[요소 번호] = 수치**로 할 수 있다.

In [30]:
x = [1,1,3,4,5]
x[1] = 2
print(x)

[1, 2, 3, 4, 5]


## 2.5.3 list의 길이

In [31]:
x = [1, 1, 2, 3, 5]
len(x)

5

## 2.5.4 연속된 정수 데이터의 작성
5에서 9까지와 같이 연속된 정수 데이터를 만들려면 range(시작숫자, 끝숫자+1)을 사용한다.

In [37]:
y = range(5, 10)
print(y[0], y[1], y[2], y[3], y[4])

5 6 7 8 9


y는 list형과 비슷하나, 실제로는 조금 다르다. 메모리를 절약한 데이터 형식인 range형이 된다. y자체를 표시하면 리스트처럼 [5, 6, 7, 8, 9]가 아니라 range(5,10)으로 표기된다.

In [36]:
print(y)
type(y)

range(5, 10)


range

range형은 list형과 같은 방법으로 요소를 참조할 수 있지만 요소를 수정할 수 없다.

In [39]:
y[2] = 2

TypeError: 'range' object does not support item assignment

In [40]:
z = list(range(5,10))
print(z)

[5, 6, 7, 8, 9]


시작숫자를 생략하고 **range(끝숫자+1)**을 입력하면 0부터 시작되는 수열이 만들어진다.

In [41]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# 2.6 tuple
## 2.6.1 tuple의 이용
배열을 나타내는 형태로 list형 이외에 tuple형이라는 배열 변수가 있다.

In [42]:
a = (1,2,3)
print(a)
type(a)

(1, 2, 3)


tuple

## 2.6.2 요소의 참조
리스트와 같은 방식을 사용한다. tuple은 list와 달리 요소를 수정할 수 없다.

In [45]:
a[1]

2

In [46]:
a[1] = 2

TypeError: 'tuple' object does not support item assignment

스스로 정의할 때에는 수정 가능한 list형을 사용하면 간편하지만, 나중에 설명할 '함수'의 출력이 여러 개인 경우 자동으로 tuple로 정리된다.

## 2.6.3 길이가 1인 tuple
(1,2)는 tuple이지만 (1)은 tuple이 아니다. ()는 연산의 순서를 나타내는 일반적인 괄호로 간주한다. 길이가 1인 tuple은 **(1,)**과 같이 쉼표를 붙인다.

In [47]:
a = (1)
type(a)

int

In [48]:
a = (1,)
type(a)

tuple

# 2.7 if문
## 2.7.1 if문의 사용

In [49]:
x = 11
if x > 10:
    print('x is')  #A1
    print('      lager than 10.')  #A2
else:
    print('x is smaller than 11')

x is
      lager than 10.


들여쓰기된 A1과 A2 모두 실행된다. 들여쓰기는 if문제 속해 있다는 의미이다. if문의 옆에 있는 'x > 10'은 True 또는 False 값을 가지는 bool형의 데이터이다.

In [50]:
x > 10

True

In [51]:
type( x > 10)

bool

## 2.7.2 비교 연산자
'>'를 비교 연산자라고 부른다. if문에서 사용하는 비교 연산자를 정리하면 다음과 같다. 연산의 결과는 모두 bool형이 된다.

비교 연산자 | 내용
--------------| --------------|
a = b | a와 b가 같다
a > b | a가 b보다 크다
a >= b | a가 b이상이다
a < b | a가 b보다 작다
a <= b | a가 b이하이다
a != b | a와 b는 다르다

여러 조건을 사용하려면 **and**와 **or**을 사용한다. 

In [52]:
x = 15
if 10 <=x and x <=20:
    print('x is between 10 and 20.')

x is between 10 and 20.


# 2.8 for문
## 2.8.1 for문의 이용

In [53]:
for i in [1, 2, 3]:
    print(i)

1
2
3


**for**문은 **for "변수" in "list 형":** 과 같은 형태이다. list에 포함된 요소의 수만큼 for문 다음의 들여쓰기 된 행이 반복 실행된다. 반복할 때마다 list의 요소가 차례대로 변수에 들어간다. list형 대신 tuple 형, range 형을 사용할 수도 있다.

In [54]:
num = [2, 4, 6, 8, 10]
for i in range(len(num)):
    num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


## 2.8.2 enumberate의 이용

In [55]:
num = [2, 4, 6, 8, 10]
for i, n in enumerate(num):
    num[i] = n * 2
print(num)

[4, 8, 12, 16, 20]


num의 index값은 i에 들어가고, num[인덱스]에 저장되어 있는 값은 n에 들어간다. enumerate은 간편하고 우아한 방법이지만, 이 책에서는 다른 프로그래밍 언어를 배운 분들도 알기 쉽도록 enumerate을 사용하지 않는 보통의 표기법으로 통일한다.

# 2.9 벡터
list형은 벡터로 사용할 수 있을까?

In [56]:
[1,2] + [3,4]

[1, 2, 3, 4]

예상과는 다른 결과를 보여준다. list형을 서로 더하면 str형과 동일하게 '+ 연산자'로 해석되어 연결된다. 벡터의 수학적 의미는 4장에서 자세히 설명한다.

## 2.9.1 넘파이의 이용
파이썬으로 벡터나 행렬을 나타내려면 Numpy라는 라이브러리를 통해 기능을 확장한다. **import**로 간단히 가져올 수 있다.

In [57]:
import numpy as np

**as np** 부분은 넘파이를 **np**로 생략해서 사용한다는 의미이다. 이후 넘파이 관련 기능은 **np,"function"**의 형태로 호출할 수 있다.

## 2.9.2 벡터의 정의
벡터(1차원 배열)는 **np.array(list 형)**으로 정의한다.

In [59]:
x = np.array([1,2,3])
x

array([1, 2, 3])

print(x)를 통해 x를 표시하면 깔끔하게 보인다.

In [60]:
print(x)

[1 2 3]


참고로, np.array형이 아니라 list형을 print로 출력하면 요소 간의 ','이 남는다.

In [62]:
y = np.array([4, 5, 6])
print(x + y)

[5 7 9]


In [63]:
type(x)

numpy.ndarray

## 2.9.3 요소의 참조
하나의 요소를 참조하려면 list형과 마찬가지로 대괄호 **[ ]**를 사용합니다.

In [64]:
x[0]

1

## 2.9.4 요소의 수정

In [65]:
x[0] = 100
print(x)

[100   2   3]


## 2.9.5 연속된 정수 벡터의 생성
np.arange(n)으로 요소의 값이 1씩 증가하는 벡터 배열을 만들 수 있다. list형의 배열을 출력하는 **range(n)**와 마찬가지로, 0부터 n-1까지의 배열을 간단히 만들 수 있다.

In [67]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [68]:
print(np.arange(5,10))

[5 6 7 8 9]


ndarray형은 list형과 마찬가지로, for문에서 list를 대신해서 사용할 수 있지만, 벡터 연산이 가능하다는 점이 다르다.
## 2.9.6 ndarray형의 주의점
ndarray형의 내용을 복사하려면 일반 변수처럼 b = a를 사용하는 것이 아니라 b = a.copy()를 사용해야 한다. 단순히 b = a와 같이 대입하면 a의 내용이 저장된 곳의 참조 주소가 전달된다. b = a를 입력한 후 b의 내용을 변경하면 그 변경 사항이 a에도 반영되어 버린다.

In [70]:
a = np.array([1,1])
b = a
print(' a = ' + str(a))
print(' b = ' + str(b))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))

 a = [1 1]
 b = [1 1]
b =[100   1]
a =[100   1]


In [73]:
a = np.array([1,1])
b = a.copy()
print(' a = {0}'.format(a))
print(' b = {0}'.format(b))
b[0] = 100
print('b = {0}'.format(b))
print('a = {0}'.format(a))

 a = [1 1]
 b = [1 1]
b = [100   1]
a = [1 1]


# 2.10 행렬
## 2.10.1 행렬의 정의
ndarray의 2차원 배열로 다음과 같이 행렬을 정의할 수 있다.

In [75]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


## 2.10.2 행렬의 크기

In [76]:
x = np.array([[1,2,3],[4,5,6]])
x.shape

(2, 3)

In [79]:
w, h = x.shape
print(w)
print(h)

2
3


In [80]:
type(x.shape)

tuple

## 2.10.3 요소의 참조

In [82]:
x = np.array([[1,2,3],[4,5,6]])
x[1,2]

6

## 2.10.4 요소의 수정

In [84]:
x = np.array([[1,2,3],[4,5,6]])
x[1,2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


## 2.10.5 요소가 0과 1인 ndarray 만들기

In [85]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [89]:
print(np.zeros((2,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 2.10.6 요소가 랜덤인 행렬 생성
요소가 랜덤(임의)인 행렬을 생성하는 경우에는 **np.random.rand(size)**를 사용한다. 각 요소는 0에서 1사이의 균일한 분포를 보이며 행렬 형태로 생성한다. 이 경우 size는 tuple이 아닌 점에 유의하라.

In [92]:
np.random.rand(2,3)

array([[0.31015545, 0.59972777, 0.94260914],
       [0.5810118 , 0.58562846, 0.60152571]])

**np.random.randn(size)**를 사용하면 평균 0 분산 1의 가우스 분포로 난수를 생성할 수 있다. 또한 **np.random.randint(low, high, size)**를 사용하면 **low**에서 **high**까지의 임의의 정숫값으로 이뤄진 **size**크기의 행렬을 생성할 수 있다.

In [93]:
np.random.randn(2,3)

array([[-0.00325963,  0.64905631, -0.94640026],
       [ 1.39637352, -0.74181155,  1.00314662]])

In [94]:
np.random.randint(1,10,(2,3))

array([[8, 5, 1],
       [7, 5, 7]])

## 2.10.7 행렬의 크기 변경

In [96]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [97]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 2.11 행렬(ndarray)의 사칙 연산
## 2.11.1 행렬의 사칙 연산

In [101]:
x = np.array([[4,4,4],[8,8,8]])
y = np.array([[1,1,1],[2,2,2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


## 2.11.2 스칼라 x 행렬

In [104]:
x = np.array([[4,4,4],[8,8,8]])
print(10 * x)

[[40 40 40]
 [80 80 80]]


## 2.11.3 산술 함수
넘파이에는 다양한 수학 함수가 준비되어 있다. 예를 들어 4장에서 설명하는 exp(x)함수는 다음과 같이 계산된다.

In [105]:
x = np.array([[4,4,4],[8,8,8]])
print(np.exp(x))

[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]


In [112]:
print(np.sqrt(x)) #제곱근
print(np.log(x)) #로그
print(np.round(np.exp(x),2)) #반올림 np.round(x,유효자릿수)
print(np.mean(x)) #평균
print(np.std(x)) #표준편차
print(np.max(x)) #최대값
print(np.min(x)) #최소값

[[2.         2.         2.        ]
 [2.82842712 2.82842712 2.82842712]]
[[1.38629436 1.38629436 1.38629436]
 [2.07944154 2.07944154 2.07944154]]
[[  54.6    54.6    54.6 ]
 [2980.96 2980.96 2980.96]]
6.0
2.0
8
4


## 2.11.4 행렬 곱의 계산

In [113]:
v = np.array([[1,2,3],[4,5,6]])
w = np.array([[1,1],[2,2],[3,3]])
print(v.dot(w))

[[14 14]
 [32 32]]


# 2.12 슬라이싱
## 2.12.1 슬라이싱의 이용
list와 ndarray에서 요소를 한 번에 나타낼 때 슬라이스라는 편리한 방법을 사용할 수 있다. 이를 잘 사용하면 프로그래밍이 간편해진다. 슬라이스는 **':'**을 사용하여 나타낸다. **변수명[:n]**명령으로 **0부터 n-1까지**의 요소를 한 번에 볼 수 있다.

In [116]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [117]:
print(x[5:])
print(x[3:8])

[5 6 7 8 9]
[3 4 5 6 7]


**변수명(n1:n2:dn]**을 입력하면 **n1에서 n2-1의 요소까지 dn 간격으로** 참조된다.

In [118]:
print(x[3:8:2])

[3 5 7]


다음과 같이 입력하면 배열 순서가 반대로 된다.

In [119]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


슬라이스는 1차원 이상의 list나 ndarrary로도 사용할 수 있다.

In [123]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(y[:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


# 2.13 조건을 만족하는 데이터의 수정
## 2.13.1 bool 배열 사용
넘파이를 통해 행렬 데이터에서 특정 조건을 만족하는 것을 추출하여 쉽게 수정할 수 있다.

In [124]:
x = np.array([1,1,2,3,5,8,13])
x > 3

array([False, False, False, False,  True,  True,  True])

In [125]:
x[x > 3]

array([ 5,  8, 13])

In [126]:
x[ x > 3] = 999
print(x)

[  1   1   2   3 999 999 999]


# 2.14 Help
## 2.14.1 Help 사용

In [127]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

# 2.15 함수
## 2.15.1 함수의 사용

In [128]:
def my_func1():
    print('Hi!')
#함수 my_func1()의 정의는 여기까지
my_func1()
# 함수를 실행

Hi!


In [129]:
def my_func2(a,b):
    c = a + b
    return c

my_func2(1,2)

3

## 2.15.2 인수와 반환값
함수에 전달할 변수를 **인수**라고 합니다. 함수의 출력은 **반환값**이라고 합니다.

In [130]:
def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m, s

In [142]:
data = np.random.randn(100)
data_mean, data_std = my_func3(data)
print('mean:{0}, std:{1}'.format(data_mean, data_std))
print('mean:{0:.2f}, std:{1:.2f}'.format(data_mean, data_std))

mean:0.054123599371127255, std:0.8698203665904188
mean:0.05, std:0.87
mean:0.05, std:0.87
mean:0.05, std:0.87
mean:0.05, std:0.87


반환값이 여러 개라도 하나의 변수로 받을 수 있다. 이 경우 반환값은 tuple형이 되고, 각 요소에 함수의 반환값이 저장된다. 난수이므로 실행할 때마다 값이 달라진다.

In [143]:
output = my_func3(data)
print(output)
print(type(output))
print('mean{0:.2f}, std{0:.2f}'.format(output[0], output[1]))

(0.054123599371127255, 0.8698203665904188)
<class 'tuple'>
mean0.05, std0.05


# 2.16 파일 저장
## 2.16.1 하나의 ndarray형을 저장
하나의 ndarray형을 파일에 저장하려면 **np.save('파일명.npy', 변수명)**을 사용한다. 파일의 확장자는 **.npy**이다.(난수이므로 실행시마다 다른 결과 저장). 데이터를 로드하려면(읽으려면) **np.load('파일명.npy')**를 사용한다.

In [144]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy',data)
data = []
print(data)
data = np.load('datafile.npy')
print(data)

[ 2.00579056 -0.32834368  0.07067079  0.63026145  0.76517883]
[]
[ 2.00579056 -0.32834368  0.07067079  0.63026145  0.76517883]


## 2.16.2 여러 ndarray형을 저장
여러 ndarray형을 저장하려면 **np.savez('파일명.npz', 변수명1 = 변수명1, 변수명2 = 변수명2, ...)**을 사용한다.

In [147]:
data1 = np.array([1,2,3])
data2 = np.array([10,20,30])
np.savez('datafile2.npz', data1=data1, data2=data2)
data1 = []
data2 = []
outfile = np.load('datafile2.npz')
print(outfile.files)
data1 = outfile['data1']
data2 = outfile['data2']
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]


데이터를 **np.load**로 불러오면 저장된 모든 변수가 **outfile**에 저장되어 **outfile['변수명']**으로 각각의 변수를 참조할 수 있다. **outfile.files**로 저장된 변수의 목록을 볼 수 있다.