# PyToch로 딥러닝 하기: 60분만에 끝장내기

PYTORCH란?

python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다.
- NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

## 시작하기

### Tensors
Tensors는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능합니다.

In [1]:
import numpy as np

x = np.array([1,2,3])
y = np.array([3,4,5])
print(x+y)

[4 6 8]


In [0]:
from __future__ import print_function  #파이썬2 -> 파이썬3 호환 가능하도록
import torch

<br/>

**초기화 되지 않은 5x3행렬을 생성합니다.**

In [3]:

x = torch.empty(5,3)
print(x)

tensor([[7.4545e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 0.0000e+00, 0.0000e+00]])


In [4]:
x = torch.rand(5,3)
print(x)

# ----------------
# y = np.random.rand(5,3)
# print(y)

tensor([[0.2990, 0.4393, 0.5547],
        [0.0017, 0.9407, 0.4938],
        [0.7741, 0.2260, 0.6450],
        [0.6303, 0.0748, 0.2474],
        [0.1090, 0.2870, 0.4080]])


**dtype이 long이고 0으로 채워진 행렬을 생성합니다.**

In [5]:
x = torch.zeros(5,3, dtype=torch.long)  #정수 32bit
print(x)

# -------------------
# y = np.zeros((5,3))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


<Br/>

**데이터로부터 tensor를 직접 생성합니다.**

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


<br/>

**또는 존재하는 tensor를 바탕으로 tensor를 만듭니다. 이 method들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용 합니다.**

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)  
print(x)

x = x.new_zeros(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


<br/>
<br/>
랜덤한 값을 가지는 텐서 생성 <br/>
- torch.rand(): 0과 1 사이의 숫자 생성 <br/>
- torch.rand_like(): 사이즈를 튜플로 입력하지 않고, 기존의 텐서로 정의 <br/>
- torch.randn(): 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 생성 <br/>
- torch.randn_like(): 사이즈를 튜플로 입력하지 않고, 기존의 텐서로 정의 <br/>
- torch.randint(): 주어진 범위 내의 정수를 균등하게 생성, 자료형은 torch.float32 <br/>
- torch.randint_like(): 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의 <br/>
- torch.randperm(): 주어진 범위 내의 정수를 랜덤하게 생성 <br/>

- torch.manual_seed(): 랜덤 생성에 사용되는 seed

In [8]:
y = torch.rand(2,3, dtype=torch.double) #실수형, 소수점 이하 15자리
print(y)
print()

x = torch.rand_like(x, dtype=torch.float)  #실수형, 소수점 이하 6자리
print(x)
print()

y = torch.randn(2,3, dtype=torch.double)
print(y)
print()

x = torch.randn_like(x, dtype=torch.float)
print(x)
print()

y = torch.randint(2,10, size=(2,3))
print(y)
print()

x = torch.randint_like(x,2,10)
print(x)
print()

y = torch.randperm(4)
print(y)

tensor([[0.6375, 0.3421, 0.8450],
        [0.7990, 0.4223, 0.8417]], dtype=torch.float64)

tensor([[0.0963, 0.2596, 0.9884],
        [0.0400, 0.1989, 0.9500],
        [0.3517, 0.6366, 0.5177],
        [0.1452, 0.6506, 0.1699],
        [0.9605, 0.1267, 0.9409]])

tensor([[-0.7322,  2.4950,  0.9227],
        [-0.7764, -1.2456,  2.6224]], dtype=torch.float64)

tensor([[ 0.3715,  0.1679, -0.6885],
        [-0.2620,  0.4258,  0.4252],
        [ 0.5452,  0.0992, -0.1951],
        [ 0.4709,  0.1843,  0.3482],
        [-0.8908, -2.2255, -0.2378]])

tensor([[5, 4, 9],
        [8, 7, 7]])

tensor([[9., 7., 9.],
        [4., 5., 4.],
        [4., 4., 4.],
        [3., 5., 8.],
        [9., 7., 3.]])

tensor([1, 0, 3, 2])


<br/>
행렬의 크기를 구합니다.

In [9]:
print(x.size())

torch.Size([5, 3])


*** torch.size는 사실 튜플(tuple)과 같으며, 모든 튜플 연산을 지원합니다.

In [10]:
# 인덱싱 하기
(x.size())[0]

5

In [11]:
# 슬라이싱 하기
x.size()[1:]

torch.Size([3])

In [12]:
# 튜플 더하기 
x.size() + x.size()

torch.Size([5, 3, 5, 3])

In [13]:
# 튜플 곱하기 
x.size() * 3

torch.Size([5, 3, 5, 3, 5, 3])

In [14]:
# 튜플 길이 구하기
len(x.size())

2

### 연산(Operations)

**덧셈: 문법1**

In [15]:
y = torch.rand(5,3)
print(x + y)

tensor([[9.5551, 7.1943, 9.8033],
        [4.9297, 5.3927, 4.8685],
        [4.8036, 4.9303, 4.4252],
        [3.8003, 5.2628, 8.2993],
        [9.4275, 7.1500, 3.5565]])


**덧셈: 문법2**

In [16]:
print(torch.add(x,y))

tensor([[9.5551, 7.1943, 9.8033],
        [4.9297, 5.3927, 4.8685],
        [4.8036, 4.9303, 4.4252],
        [3.8003, 5.2628, 8.2993],
        [9.4275, 7.1500, 3.5565]])


**덧셈: 결과 tensor를 인자로 제공**

In [17]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[9.5551, 7.1943, 9.8033],
        [4.9297, 5.3927, 4.8685],
        [4.8036, 4.9303, 4.4252],
        [3.8003, 5.2628, 8.2993],
        [9.4275, 7.1500, 3.5565]])


**덧셈: 바꿔치기(In-place) 방식

In [18]:
# y에 x 더하기
y.add_(x)
print(y)

tensor([[9.5551, 7.1943, 9.8033],
        [4.9297, 5.3927, 4.8685],
        [4.8036, 4.9303, 4.4252],
        [3.8003, 5.2628, 8.2993],
        [9.4275, 7.1500, 3.5565]])


*** 바꿔치기(In-place) 방식으로 tensor의 값을 변경하는 연산은 "_"를 접미사로 갖습니다. 
ex) x.copy_(y), x.t_()는 x를 변경합니다. 

In [19]:
print(x[:,1])

tensor([7., 5., 4., 5., 7.])


<br/>

**크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view를 사용합니다.**

In [20]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # -1은 다른 차원들을 사용하여 유추합니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


<br/>

**만약 tensor에 하나의 값만 존재한다면, .item()을 사용하면 숫자 값을 얻을 수 있습니다.**

In [21]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.5894])
1.5894396305084229


## NumPy 변환(Bridge)

Torch Tensor를 Numpy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.
(CPU 상의) Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

### Torch Tensor를 NumPy 배열로 변환하기


In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy 배열의 값이 어떻게 변하는지 확인해보세요.

In [24]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### NumPy 배열을 Torch Tensor로 변환하기

NumPy(np) 배열을 변경하면 Torch의 값도 자동 변경되는 것을 확인해보세요.

In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


<br/>
CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, 반대 변환도 지원합니다.

<br/>

## CUDA Tensors

<br/>

**.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.**

In [26]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# torch.device를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.

if torch.cuda.is_available():
  device = torch.device("cuda")  # CUDA 장치 객체(device object)로
  y = torch.ones_like(x, device=device) # GPU 상에 직접적으로 tensor를 생성하거나
  x = x.to(device) # .to("cuda")를 사용하면 됩니다.
  z = x + y
  print(z)
  print(z.to("cpu", torch.double))  # .to는 dtype도 함께 변경합니다.

tensor([2.5894], device='cuda:0')
tensor([2.5894], dtype=torch.float64)
