# Linear Regression

In [8]:
import numpy as np
import torch
import torch.nn.functional as F
import torch.optim as optim

In [11]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

W = torch.zeros(1, requires_grad=True) #require_grad는 학습할 것이라고 알려줌
b = torch.zeros(1, requires_grad=True)


In [12]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [13]:
#loss(Mean Square Error)
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [14]:
optimizer = optim.SGD([W, b], lr=0.01)  #parameter list로 만들어서 넣어줌

optimizer.zero_grad()  #zero_grad로 gradient 초기화
cost.backward() #gradient 계산 
optimizer.step() #step()으로 개선

In [16]:
print(W)
print(b)

tensor([0.1867], requires_grad=True)
tensor([0.0800], requires_grad=True)


hypothersis가 더 나아졌는지 확인

In [18]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.2667],
        [0.4533],
        [0.6400]], grad_fn=<AddBackward0>)


In [19]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(14.7710, grad_fn=<MeanBackward0>)


## Full Code

In [24]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

W = torch.zeros(1, requires_grad=True) #require_grad는 학습할 것이라고 알려줌
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.01)

np_epochs = 1000
for epoch in range(np_epochs + 1):
    
    #H(x) 계산
    hypothesis = x_train * W + b
    
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    # cost로 H(x) 계선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    #100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:3d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(epoch, np_epochs, W.item(), b.item(), cost.item()))
print(W)

Epoch   0/1000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch 100/1000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch 200/1000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch 300/1000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch 400/1000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch 500/1000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch 600/1000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch 700/1000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch 800/1000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch 900/1000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1000 W: 1.971, b: 0.066 Cost: 0.000633
tensor([1.9709], requires_grad=True)


## SGD 직접 구현

In [27]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 모델 초기화
W = torch.zeros(1)

#learning rate 설정
lr = 0.1

nb_epochs = 10
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = y_train * W
    
    # cost gradient 계산
    cost = torch.mean((hypothesis - y_train) **2)
    gradient = torch.sum((W * x_train - y_train) * x_train)
    
    print('Epoch {:4d}/{}, W: {:.3f}, Cost: {:.6f}'.format(epoch, nb_epochs, W.item(), cost.item()))
    
    #cost gradient로 H(x) 개선
    W -= lr * gradient

Epoch    0/10, W: 0.000, Cost: 18.666666
Epoch    1/10, W: 2.800, Cost: 60.479992
Epoch    2/10, W: 1.680, Cost: 8.631467
Epoch    3/10, W: 2.128, Cost: 23.751167
Epoch    4/10, W: 1.949, Cost: 16.804136
Epoch    5/10, W: 2.020, Cost: 19.439077
Epoch    6/10, W: 1.992, Cost: 18.362087
Epoch    7/10, W: 2.003, Cost: 18.789202
Epoch    8/10, W: 1.999, Cost: 18.617767
Epoch    9/10, W: 2.001, Cost: 18.686243
Epoch   10/10, W: 2.000, Cost: 18.658838


## 다차원으로 확장

In [45]:
x_train = torch.FloatTensor([[73, 80, 75], 
                             [92, 88, 93], 
                             [89, 91, 90], 
                             [96, 98, 100], 
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad = True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr = 1e-5)


np_epochs = 20
for epoch in range(np_epochs + 1):
    #H(x) 계산
    #hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 +b
    hypothesis = x_train.matmul(W) + b 
    
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(epoch, np_epochs, hypothesis.squeeze().detach(), cost.item()))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2038, 80.4776, 79.5864, 86.6683, 61.6065]) Cost: 9322.951172
Epoch    2/20 hypothesis: tensor([104.8773, 125.5926, 124.2017, 135.2536,  96.1426]) Cost: 2931.251953
Epoch    3/20 hypothesis: tensor([125.9965, 150.8837, 149.2125, 162.4900, 115.5034]) Cost: 922.593262
Epoch    4/20 hypothesis: tensor([137.8355, 165.0618, 163.2332, 177.7584, 126.3570]) Cost: 291.350159
Epoch    5/20 hypothesis: tensor([144.4721, 173.0100, 171.0930, 186.3176, 132.4417]) Cost: 92.974937
Epoch    6/20 hypothesis: tensor([148.1923, 177.4658, 175.4991, 191.1158, 135.8529]) Cost: 30.632730
Epoch    7/20 hypothesis: tensor([150.2776, 179.9637, 177.9690, 193.8056, 137.7653]) Cost: 11.040657
Epoch    8/20 hypothesis: tensor([151.4464, 181.3642, 179.3536, 195.3134, 138.8376]) Cost: 4.883067
Epoch    9/20 hypothesis: tensor([152.1014, 182.1494, 180.1297, 196.1586, 139.4389]) Cost: 2.947450
Epoch   10/20 hypo

# nn.Module: w와 b를 일일이 쓰는 것은 힘들므로 편리한 모듈 제공

- nn.Module을 상속해서 모델 생성
- nn.Linear(3,1)
-> 입력 차원: 3, 출력차원: 1
- Hypothesis 계산은 forward() 에서!
- gradient 계산은 PyTorch가 알아서 해준다 backward()

In [47]:
import torch.nn as nn

class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)
        
        def forward(Self, x):
            return self.linear(x)
        
#hypothesis = model(x_train)


# ---------------------
# 모델 초기화
#W = torch.zeros((3, 1), requires_grad = True)
#b = torch.zeros(1, requires_grad=True)

#H(x) 계산
#hypothesis = x_train.matmul(W) + b 

## F.mse_loss

- torch.nn.functional에서 제공하는 loss function 사용
- 쉽게 다른 loss와 교체 가능!(l1_loss, smooth_l1_loss 등...)

In [51]:
import torch.nn.functional as F

# cost 계산
#cost = F.mse_loss(prediction, y_train)   -> cost = torch.mean((hypothesis - y_train) ** 2)와 같음

NameError: name 'prediction' is not defined

## Full Code

In [55]:
x_train = torch.FloatTensor([[73, 80, 75], 
                             [92, 88, 93], 
                             [89, 91, 90], 
                             [96, 98, 100], 
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모델 초기화
#model = MultivariateLinearRegressionModel()

# optimizer 설정
#optimizer = optim.SGD([W,b], lr=1e-5)

np_epochs = 20
#for epoch in range(np_epochs + 1):
    #H(x) 계산
    #hypothesis = x_train.matmul(W) + b 
    #hypothesis = model(x_train)
    
    # cost 계산
    #cost = torch.mean((hypothesis - y_train) ** 2)
    #cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    #optimizer.zero_grad()
    #cost.backward()
    #optimizer.step()
    
