# View (Reshape)

In [1]:
import numpy as np
import torch

In [2]:
t = np.array([[[0, 1, 2], 
               [3,4,5]], 
              
              [[6,7,8], 
              [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [3]:
print(ft.view([-1, 3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [4]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze: 자동으로 그 dimension의  element가 하나만 남아 있는 경우 없애주는 역할

In [5]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [6]:
print(ft.squeeze()) #(3,1)에서 1인 dimension 1은 사라짐
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

In [2]:
ft = torch.Tensor([0, 1, 2])
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [8]:
print(ft.unsqueeze(0)) #0 dimension에 element 1을 넣어라
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [9]:
print(ft.view(1, -1)) 
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [10]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [11]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

In [12]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [13]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [14]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


## Concatenate

In [40]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [43]:
print(torch.cat([x,y], dim=0))  #dimension 0이 늘어남
print(torch.cat([x,y], dim=1))
print(torch.cat([x,y]))

print(torch.stack([x,y]))
print(torch.stack([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])


## Stacking

In [5]:
x= torch.FloatTensor([1,4])
print(x)
print(x.shape)
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

tensor([1., 4.])
torch.Size([2])


In [28]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
print(x.unsqueeze(0)) # 0 dimension에 element 1 넣어라
print(x.unsqueeze(0).shape)

tensor([[1., 4.]])
torch.Size([1, 2])


In [49]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros

In [52]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [53]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation

In [54]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [55]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))  #메모리 새로 선언하지 않고, 기존 텐서 값에 넣는다.
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
